### PR TITLE
feat: Add Breadcrumb Navigation to Marketplace

### LINKED ISSUE #52: Add Breadcrumb Navigation to Marketplace
## 📘 Description

Users are currently struggling to navigate the marketplace due to the lack of clear navigation that indicates their current location. Adding a breadcrumb navigation will enhance the user experience by providing a simple way to return to previous pages or navigate back to the landing page. Additionally, aligning the breadcrumb navigation with the "Add Product" button will help maintain a visually cohesive and organized layout.

## 🔢 **Steps**

1. Create a new file named `breadcrumb-navigation.tsx` inside the `components/ui` directory.
2. Name the component `BreadcrumbNavigation`.
3. Implement the navigation using the shadcn/ui breadcrumb component.
4. Configure the "Home" breadcrumb to redirect users to the landing page.
5. Align the breadcrumbs with the "Add Product" button.
6. Ensure the navigation is responsive and functional.

## ✅ Acceptance Criteria

- Breadcrumb navigation must be correctly implemented and functional.
- The "Home" breadcrumb must redirect to the landing page.
- Breadcrumbs must be aligned with the "Add Product" button.
- The design must be responsive and consistent across all devices.

## 🌎 References

- [shadcn/ui breadcrumb](https://ui.shadcn.com/docs/components/breadcrumb)
- [Lucide Icons](https://lucide.dev/icons/)

image

## 📜 Additional Notes

⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

### PR DESCRIPTION
**Pull request by Josue19-08**
# 📝 Add Breadcrumb Navigation to Marketplace

## 🛠️ Issue
- Closes [#52](https://github.com/KaizeNodeLabs/SafeSwap/issues/52)

## 📖 Description
A breadcrumb navigation was implemented for the **Marketplace**, providing a clearer and more organized user experience when navigating within the page. The solution involved creating a dedicated breadcrumb navigation component.

## ✅ Changes made
- Created a new file **`breadcrumb-navigation.tsx`** in the `components/ui` directory.
- Added the **BreadcrumbNavigation** component to the **`page.tsx`** file in the **Marketplace**.
- Styled the breadcrumb to meet visual requirements:
  - "Home" appears in gray.
  - "Marketplace" appears in black with a lighter font weight for reduced intensity.

## 🖼️ Media (screenshots/videos)
image
image

## 📜 Additional Notes
Additionally, the attached image in the issue description showed that the "Add Product" button included an icon, which has now been added to the button.
image

During the push process to the remote repository, the `pre-push` hook from **lefthook v1.8.2** got stuck at the build stage. The command used was:

```bash
PS C:\SafeSwap\SafeSwap-Josue> git push origin feat/breadcrumb-navigation-marketplace
╭────────────────────────────────────╮
│ 🥊 lefthook v1.8.2  hook: pre-push │
╰────────────────────────────────────╯
⠧ waiting: build

### CODE REVIEW

**Comment by Josue19-08** [comment]
@danielcdz Hi sir! Could you review the PR, please?

**Review by danielcdz — APPROVED** [review]
LGTM

**Review by derianrddev — APPROVED** [review]
@Josue19-08 Could you please resolve the conflicts? after that we can merge, good job, thank you!

**Comment by Josue19-08** [comment]
@derianrddev Working on it!

**Comment by Josue19-08** [comment]
@derianrddev Conflicts resolved!

**Comment by derianrddev** [comment]
@Josue19-08 Ready! merged

**Comment by Josue19-08** [comment]
Thank you! @derianrddev @danielcdz

**Pull request merged**
