### PR TITLE
feat/add safe swap logo

### LINKED ISSUE #31: Add SafeSwap to landing page
# 📘 Issue Description
**Enhance the Landing Page with SafeSwap Branding**

The current landing page lacks any visual identity or branding for SafeSwap. To establish a strong brand presence, we want to incorporate the "SafeSwap" title prominently on the page. Since we don’t yet have a logo, feel free to experiment with different font styles and placements.

**Task Details:**
1. Propose 2-3 design options where the "SafeSwap" title is effectively integrated into the landing page.
   - **Option 1**: Place the title prominently in the header/navigation bar for consistent visibility.
   - **Option 2**: Feature the title as a central hero element on the page, paired with a tagline or key message.
   - **Option 3**: Include the title in the footer or as a watermark-like element for subtle branding.

2. Experiment with different font types and sizes to explore distinct styles that align with SafeSwap's vision.

3. Present mockups or design sketches for each option to aid in decision-making.

**Notes:**
- Ensure the title is visually appealing and blends seamlessly with the current landing page design.
- Focus on creating a strong and professional look that resonates with users.
- Keep the designs responsive and adaptable to various screen sizes.

### PR DESCRIPTION
**Pull request by 0xdevcollins**
# 📝 feat/add safe swap logo

## 🛠️ Issue
- Closes #31

## 📖 Description
- Added dynamic SafeSwap logo integration across the application, supporting light and dark themes. 
- Ensured seamless theme switching with state persistence using `localStorage`.

## ✅ Changes made
- Added the svg logos to public/images
- Created `SafeSwapLogo` component for reusable and responsive logo rendering.

## 📜 Additional Notes
- Tested the implementation for accessibility and responsiveness.
- The logo transitions smoothly between light and dark versions based on the current theme.

### CODE REVIEW

**Comment by 0xdevcollins** [comment]
Dark
Light

**Comment by 0xdevcollins** [comment]
Link to the logo usage docs 
https://github.com/KaizeNodeLabs/SafeSwap/blob/676240579ce5b8b5b0a98d7a96e9051b3252b193/logo-usage.md

**Comment by danielcdz** [comment]
Hey @0xdevcollins This looks awesome! can you please add this to the main page and remove the duplicated SafeSwap logo on the footer?


image

**Comment by 0xdevcollins** [comment]
> Hey @0xdevcollins This looks awesome! can you please add this to the main page and remove the duplicated SafeSwap logo on the footer?
> 
> image

Okay

**Comment by 0xdevcollins** [comment]
@danielcdz please review

**Review by danielcdz — APPROVED** [review]

**Pull request merged**
