### PR TITLE
chore: add connect button to markerplace

### LINKED ISSUE #13: Add connect to wallet button in marketplace page
# 📘 Issue Description
- In the landing page there is a button to connect the wallet, we want to have this same button in the marketplace page.
## ✅ Acceptance Criteria
- There is a button to connect your wallet in the marketplace page.
- This button is not required to work yet.

### PR DESCRIPTION
**Pull request by zintarh**
# 📝 Add connect button to marketplace

## 🛠️ Issue
- Closes #13 

## 📖 Description
- 

## ✅ Changes made
- 

## 📜 Additional Notes
-

### CODE REVIEW

**Comment by danielcdz** [comment]
Hello @zintarh can you add a screenshot to see how it looks?

**Comment by danielcdz** [comment]
@zintarh any updates?

**Comment by zintarh** [comment]
@danielcdz 
Screenshot 2024-11-25 at 12 01 51 AM

**Comment by danielcdz** [comment]
Awesome! can you resolve the conflicts? then I can merge this PR

**Comment by zintarh** [comment]
@danielcdz  conflict is resolved. Thank you

**Comment by danielcdz** [comment]
@zintarh new conflicts appeared can you solve them one last time 🙏

**Review by danielcdz — APPROVED** [review]

**Comment by zintarh** [comment]
> @zintarh new conflicts appeared can you solve them one last time 🙏

Alright

**Comment by zintarh** [comment]
@danielcdz Conflict is resolved

**Pull request merged**
