### PR TITLE
Feat/add safeswap landing page

### LINKED ISSUE #18: Add SafeSwap to landing page
# 📘 Issue Description
**Enhance the Landing Page with SafeSwap Branding**

The current landing page lacks any visual identity or branding for SafeSwap. We want to incorporate the "SafeSwap" title prominently on the page to establish a strong brand presence. Since we don’t yet have a logo, feel free to experiment with different font styles and placements.

**Task Details:**
1. Propose 2-3 design options where the "SafeSwap" title is effectively integrated into the landing page.
   - **Option 1**: Place the title prominently in the header/navigation bar for consistent visibility.
   - **Option 2**: Feature the title as a central hero element on the page, paired with a tagline or key message.
   - **Option 3**: Include the title in the footer or as a watermark-like element for subtle branding.

2. Experiment with different font types and sizes to explore distinct styles that align with SafeSwap's vision.

3. Present mockups or design sketches for each option to aid in decision-making.

**Notes:**
- Ensure the title is visually appealing and blends seamlessly with the current landing page design.
- Focus on creating a strong and professional look that resonates with users.
- Keep the designs responsive and adaptable to various screen sizes.

### PR DESCRIPTION
**Pull request by JosueBrenes**
# 📝 Pull Request Title

`fix: resolve no-empty-interface lint error in Input component`
`feat: add safeswap to landing page`

## 🛠️ Issue
- Closes #18 

## 📖 Description
- This pull request fixes the ESLint `@typescript-eslint/no-empty-object-type` error in the `Input` component by removing the unnecessary `InputProps` interface and directly using `React.InputHTMLAttributes<HTMLInputElement>`.
- Additionally, it includes updates to the hero section of the application to enhance its visual appeal and consistency.

## ✅ Changes made
- Removed the `InputProps` interface declaration.
- Updated `React.forwardRef` in the `Input` component to use `React.InputHTMLAttributes<HTMLInputElement>` directly.
- Updated the following content in the `hero-section` component located at `frontend\app\components\ui\hero-section.tsx`:

## 📷 Evidence

image

## 📜 Additional Notes
- The fix simplifies the component and aligns with ESLint rules for better maintainability.

### CODE REVIEW

**Comment by danielcdz** [comment]
@JosueBrenes can you resolve the conflicts you have?

**Comment by danielcdz** [comment]
Also can you add screenshots of how it looks the changes you added please

**Comment by danielcdz** [comment]
@JosueBrenes can you update your branch again please 👍

**Comment by danielcdz** [comment]
Is the title `SafeSwap` or SafesWap` ? Cause in the code I see the first option but in the screenshot I see the 2nd one

**Comment by JosueBrenes** [comment]
Ready @danielcdz

**Review by danielcdz — APPROVED** [review]
LGTM

**Pull request merged**
