### PR TITLE
Fix: GA Auto assign prs

### PR DESCRIPTION
**Pull request by lauchaves**
# 📝 Pull Request Title
GA Auto assign prs

## 🛠️ Issue
- Closes #

## 📖 Description
- Fix kentaro-m/auto-assign-action@v2.0.0 changed and ga its failing 

## ✅ Changes made
- Updated ga to use github-script@v6 instead

## 📜 Additional Notes
- N/A

### CODE REVIEW

**Comment by lauchaves** [comment]
@danielcdz hey, I noticed some issues with the auto assign, bumping a fix for it here, lmk any feedback

**Comment by danielcdz** [comment]
Hey @lauchaves The check is retrieving this error: 

image

**Comment by lauchaves** [comment]
I'll check it

**Comment by lauchaves** [comment]
@danielcdz updated

**Pull request merged**
