### PR TITLE
 feat: improve escrow card on landing page

### LINKED ISSUE #32: Improve card description in Landing Page
## Overview
image

The landing page includes a section highlighting the features provided by the marketplace. To enhance clarity and showcase transparency, we want to update the escrow-related section with additional information.

## Tasks
- Add a Reference to [Trustless Work API](https://www.trustlesswork.com/)
- Update the escrow-related section to explicitly mention the use of the Trustless Work API for managing smart contracts.
- Highlight its role in enabling trustless and secure transactions.
- Improve the Description:
   - Refine the current content to clearly explain the benefits of using the Trustless Work API within the marketplace ecosystem.
- Include a Link to Their Website:
   - Add a clickable link to the Trustless Work API's official website for users to learn more about the service.

### PR DESCRIPTION
**Pull request by Iwueseiter**
## 🛠️ Issue
- Closes #32

### CODE REVIEW

**Comment by danielcdz** [comment]
@Iwueseiter can you attach a screenshot of how it looks?

**Comment by Iwueseiter** [comment]
> @Iwueseiter can you attach a screenshot of how it looks?

Screenshot 2024-11-29 062653

**Comment by danielcdz** [comment]
Is it possible to add this link: https://www.trustlesswork.com/ as ab href or something similar in that description? @Iwueseiter

**Comment by Iwueseiter** [comment]
> Is it possible to add this link: https://www.trustlesswork.com/ as ab href or something similar in that description? @Iwueseiter

The link can be added in the description but users will have to copy it to their browsers. It won’t be clickable.

**Comment by Iwueseiter** [comment]
> > Is it possible to add this link: https://www.trustlesswork.com/ as ab href or something similar in that description? @Iwueseiter
> 
> The link can be added in the description but users will have to copy it to their browsers. It won’t be clickable.

Screenshot 2024-11-29 154031

**Review by danielcdz — APPROVED** [review]

**Pull request merged**
